package cl.littlephoenix.itunessearch.models.response

class DetailResponse(val wrapperType: String,
                     val artistType: String,
                     val artistName: String,
                     val artistLinkUrl: String,
                     val artistId: Long,
                     val amgArtistId: Long,
                     val primaryGenreName: String,
                     val primaryGenreId: Long,
                     val collectionType: String,
                     val collectionId: Long,
                     val collectionName: String,
                     val collectionCensoredName: String,
                     val artistViewUrl: String,
                     val collectionViewUrl: String,
                     val artworkUrl60: String,
                     val artworkUrl100: String,
                     val collectionPrice: Float,
                     val collectionExplicitness: String,
                     val trackCount: Int,
                     val copyright: String,
                     val country: String,
                     val currency: String,
                     val releaseDate: String)
